movieproject/movieapp/urls.py
from . import views
from django.urls import path
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to="gallery")
    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import movie

class movieform(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','image']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import movie
from .forms import movieform

# Create your views here.
def index(request):
    movie1=movie.objects.all()
    return render(request,"index.html",{'movie_list':movie1})

def details(request,movie_id):
    movie2=movie.objects.get(id=movie_id)
    return render(request,"details.html",{'movie':movie2})

def add_movie(request):
    if request.method=="POST":
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        image = request.FILES['image']
        movies=movie(name=name,desc=desc,year=year,image=image)
        movies.save()
    return render(request,'add.html')

def update(request,id):
    movies=movie.objects.get(id=id)
    form=movieform(request.POST or None,request.FILES,instance=movies)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movies})

def delete(request,id):
    if request.method=='POST':
        movies=movie.objects.get(id=id)
        movies.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter your movie name"><br>
    <input type="text" name="desc" placeholder="enter your movie desc"><br>
    <input type="text" name="year" placeholder="enter your movie year"><br>
    <input type="file" name="image" ><br>
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- As a link -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Online Movies
  </a>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

movieproject/templates/delete.html
<form method="POST">

  {% csrf_token %}
  Are You Want To Delete The Third Movie?
  <input type="submit">
</form>

movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.image.url}}" width="300" height="300">
        </div>
            <div class="col-md-6">
            <h4>{{movie.name}}</h4>
            <h6>{{movie.desc}}</h6>
            <h6>{{movie.year}}</h6>
                <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
                <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
            </div>
    </div>
</div>

{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}

        <div class="col-md-3">
            <div class="card" style="width:17rem; height:30rem">
  <img class="card-img-top " src="{{i.image.url}}" alt="" height="250" >
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:details' i.id %}" class="btn btn-warning">View Detail</a>
  </div>

</div>
        </div>
        {% endfor %}
    </div>
</div>
<br>

<p>Add To Another Movie Please Click Here  <a class="btn btn-warning"  href="{% url 'movieapp:add_movie' %}" >Add</a>  </p>

{% endblock %}